//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WashEEntities : DbContext
    {
        public WashEEntities()
            : base("name=WashEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
        public virtual DbSet<tbCatalogoProductos> tbCatalogoProductos { get; set; }
        public virtual DbSet<tbPrecios> tbPrecios { get; set; }
        public virtual DbSet<tbProductos> tbProductos { get; set; }
        public virtual DbSet<tbServicios> tbServicios { get; set; }
        public virtual DbSet<tbTipoVehiculo> tbTipoVehiculo { get; set; }
        public virtual DbSet<tbAcciones> tbAcciones { get; set; }
        public virtual DbSet<tbAccionRol> tbAccionRol { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
    
        public virtual ObjectResult<string> UDP_Persona_tbPersonas_Habilitar(Nullable<int> per_Id, Nullable<int> per_UsuarioModifica, Nullable<System.DateTime> per_FechaModifica)
        {
            var per_IdParameter = per_Id.HasValue ?
                new ObjectParameter("per_Id", per_Id) :
                new ObjectParameter("per_Id", typeof(int));
    
            var per_UsuarioModificaParameter = per_UsuarioModifica.HasValue ?
                new ObjectParameter("per_UsuarioModifica", per_UsuarioModifica) :
                new ObjectParameter("per_UsuarioModifica", typeof(int));
    
            var per_FechaModificaParameter = per_FechaModifica.HasValue ?
                new ObjectParameter("per_FechaModifica", per_FechaModifica) :
                new ObjectParameter("per_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Persona_tbPersonas_Habilitar", per_IdParameter, per_UsuarioModificaParameter, per_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Persona_tbPersonas_Inactivar(Nullable<int> per_Id, string per_RazonInactivo, Nullable<int> per_UsuarioModifica, Nullable<System.DateTime> per_FechaModifica)
        {
            var per_IdParameter = per_Id.HasValue ?
                new ObjectParameter("per_Id", per_Id) :
                new ObjectParameter("per_Id", typeof(int));
    
            var per_RazonInactivoParameter = per_RazonInactivo != null ?
                new ObjectParameter("per_RazonInactivo", per_RazonInactivo) :
                new ObjectParameter("per_RazonInactivo", typeof(string));
    
            var per_UsuarioModificaParameter = per_UsuarioModifica.HasValue ?
                new ObjectParameter("per_UsuarioModifica", per_UsuarioModifica) :
                new ObjectParameter("per_UsuarioModifica", typeof(int));
    
            var per_FechaModificaParameter = per_FechaModifica.HasValue ?
                new ObjectParameter("per_FechaModifica", per_FechaModifica) :
                new ObjectParameter("per_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Persona_tbPersonas_Inactivar", per_IdParameter, per_RazonInactivoParameter, per_UsuarioModificaParameter, per_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Persona_tbPersonas_Insert(string per_Identidad, string per_Nombres, string per_Apellidos, Nullable<System.DateTime> per_FechaNacimiento, string per_Sexo, string per_Telefono, string per_CorreoElectronico, string per_EstadoCivil, Nullable<int> per_UsuarioCrea, Nullable<System.DateTime> per_FechaCrea)
        {
            var per_IdentidadParameter = per_Identidad != null ?
                new ObjectParameter("per_Identidad", per_Identidad) :
                new ObjectParameter("per_Identidad", typeof(string));
    
            var per_NombresParameter = per_Nombres != null ?
                new ObjectParameter("per_Nombres", per_Nombres) :
                new ObjectParameter("per_Nombres", typeof(string));
    
            var per_ApellidosParameter = per_Apellidos != null ?
                new ObjectParameter("per_Apellidos", per_Apellidos) :
                new ObjectParameter("per_Apellidos", typeof(string));
    
            var per_FechaNacimientoParameter = per_FechaNacimiento.HasValue ?
                new ObjectParameter("per_FechaNacimiento", per_FechaNacimiento) :
                new ObjectParameter("per_FechaNacimiento", typeof(System.DateTime));
    
            var per_SexoParameter = per_Sexo != null ?
                new ObjectParameter("per_Sexo", per_Sexo) :
                new ObjectParameter("per_Sexo", typeof(string));
    
            var per_TelefonoParameter = per_Telefono != null ?
                new ObjectParameter("per_Telefono", per_Telefono) :
                new ObjectParameter("per_Telefono", typeof(string));
    
            var per_CorreoElectronicoParameter = per_CorreoElectronico != null ?
                new ObjectParameter("per_CorreoElectronico", per_CorreoElectronico) :
                new ObjectParameter("per_CorreoElectronico", typeof(string));
    
            var per_EstadoCivilParameter = per_EstadoCivil != null ?
                new ObjectParameter("per_EstadoCivil", per_EstadoCivil) :
                new ObjectParameter("per_EstadoCivil", typeof(string));
    
            var per_UsuarioCreaParameter = per_UsuarioCrea.HasValue ?
                new ObjectParameter("per_UsuarioCrea", per_UsuarioCrea) :
                new ObjectParameter("per_UsuarioCrea", typeof(int));
    
            var per_FechaCreaParameter = per_FechaCrea.HasValue ?
                new ObjectParameter("per_FechaCrea", per_FechaCrea) :
                new ObjectParameter("per_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Persona_tbPersonas_Insert", per_IdentidadParameter, per_NombresParameter, per_ApellidosParameter, per_FechaNacimientoParameter, per_SexoParameter, per_TelefonoParameter, per_CorreoElectronicoParameter, per_EstadoCivilParameter, per_UsuarioCreaParameter, per_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Persona_tbPersonas_Update(Nullable<int> per_Id, string per_Identidad, string per_Nombres, string per_Apellidos, Nullable<System.DateTime> per_FechaNacimiento, string per_Sexo, string per_Telefono, string per_CorreoElectronico, string per_EstadoCivil, Nullable<int> per_UsuarioModifica, Nullable<System.DateTime> per_FechaModifica)
        {
            var per_IdParameter = per_Id.HasValue ?
                new ObjectParameter("per_Id", per_Id) :
                new ObjectParameter("per_Id", typeof(int));
    
            var per_IdentidadParameter = per_Identidad != null ?
                new ObjectParameter("per_Identidad", per_Identidad) :
                new ObjectParameter("per_Identidad", typeof(string));
    
            var per_NombresParameter = per_Nombres != null ?
                new ObjectParameter("per_Nombres", per_Nombres) :
                new ObjectParameter("per_Nombres", typeof(string));
    
            var per_ApellidosParameter = per_Apellidos != null ?
                new ObjectParameter("per_Apellidos", per_Apellidos) :
                new ObjectParameter("per_Apellidos", typeof(string));
    
            var per_FechaNacimientoParameter = per_FechaNacimiento.HasValue ?
                new ObjectParameter("per_FechaNacimiento", per_FechaNacimiento) :
                new ObjectParameter("per_FechaNacimiento", typeof(System.DateTime));
    
            var per_SexoParameter = per_Sexo != null ?
                new ObjectParameter("per_Sexo", per_Sexo) :
                new ObjectParameter("per_Sexo", typeof(string));
    
            var per_TelefonoParameter = per_Telefono != null ?
                new ObjectParameter("per_Telefono", per_Telefono) :
                new ObjectParameter("per_Telefono", typeof(string));
    
            var per_CorreoElectronicoParameter = per_CorreoElectronico != null ?
                new ObjectParameter("per_CorreoElectronico", per_CorreoElectronico) :
                new ObjectParameter("per_CorreoElectronico", typeof(string));
    
            var per_EstadoCivilParameter = per_EstadoCivil != null ?
                new ObjectParameter("per_EstadoCivil", per_EstadoCivil) :
                new ObjectParameter("per_EstadoCivil", typeof(string));
    
            var per_UsuarioModificaParameter = per_UsuarioModifica.HasValue ?
                new ObjectParameter("per_UsuarioModifica", per_UsuarioModifica) :
                new ObjectParameter("per_UsuarioModifica", typeof(int));
    
            var per_FechaModificaParameter = per_FechaModifica.HasValue ?
                new ObjectParameter("per_FechaModifica", per_FechaModifica) :
                new ObjectParameter("per_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Persona_tbPersonas_Update", per_IdParameter, per_IdentidadParameter, per_NombresParameter, per_ApellidosParameter, per_FechaNacimientoParameter, per_SexoParameter, per_TelefonoParameter, per_CorreoElectronicoParameter, per_EstadoCivilParameter, per_UsuarioModificaParameter, per_FechaModificaParameter);
        }
    
        public virtual int SDP_Seg_GetObjetos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SDP_Seg_GetObjetos");
        }
    
        public virtual int SDP_Seg_GetObjetosAsignados(Nullable<int> rol_Id)
        {
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SDP_Seg_GetObjetosAsignados", rol_IdParameter);
        }
    
        public virtual int SDP_Seg_GetObjetosDisponibles(Nullable<int> rol_Id)
        {
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SDP_Seg_GetObjetosDisponibles", rol_IdParameter);
        }
    
        public virtual int SDP_Seg_GetReportes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SDP_Seg_GetReportes");
        }
    
        public virtual int SDP_Seg_GetRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SDP_Seg_GetRoles");
        }
    
        public virtual int SDP_Seg_GetRolesAsignados(Nullable<int> usu_Id)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SDP_Seg_GetRolesAsignados", usu_IdParameter);
        }
    
        public virtual int SDP_Seg_GetRolesDisponibles(Nullable<int> usu_Id)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SDP_Seg_GetRolesDisponibles", usu_IdParameter);
        }
    
        public virtual int SDP_Seg_GetUserRols(Nullable<int> usu_Id, string obj_Pantalla)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var obj_PantallaParameter = obj_Pantalla != null ?
                new ObjectParameter("obj_Pantalla", obj_Pantalla) :
                new ObjectParameter("obj_Pantalla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SDP_Seg_GetUserRols", usu_IdParameter, obj_PantallaParameter);
        }
    
        public virtual int UDP_Seg_Login(string usuarioId, string password)
        {
            var usuarioIdParameter = usuarioId != null ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_Login", usuarioIdParameter, passwordParameter);
        }
    
        public virtual int UDP_Seg_tbAccesoRol_Delete(Nullable<int> rol_Id, Nullable<int> obj_Id)
        {
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var obj_IdParameter = obj_Id.HasValue ?
                new ObjectParameter("obj_Id", obj_Id) :
                new ObjectParameter("obj_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbAccesoRol_Delete", rol_IdParameter, obj_IdParameter);
        }
    
        public virtual int UDP_Seg_tbAccesoRol_Insert(Nullable<int> rol_Id, Nullable<int> obj_Id, Nullable<int> usuarioCrea, Nullable<System.DateTime> fechaCrea)
        {
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var obj_IdParameter = obj_Id.HasValue ?
                new ObjectParameter("obj_Id", obj_Id) :
                new ObjectParameter("obj_Id", typeof(int));
    
            var usuarioCreaParameter = usuarioCrea.HasValue ?
                new ObjectParameter("UsuarioCrea", usuarioCrea) :
                new ObjectParameter("UsuarioCrea", typeof(int));
    
            var fechaCreaParameter = fechaCrea.HasValue ?
                new ObjectParameter("FechaCrea", fechaCrea) :
                new ObjectParameter("FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbAccesoRol_Insert", rol_IdParameter, obj_IdParameter, usuarioCreaParameter, fechaCreaParameter);
        }
    
        public virtual int UDP_Seg_tbAccesoRol_Update(Nullable<int> acrol_Id, Nullable<int> rol_Id, Nullable<int> obj_Id, Nullable<int> acrol_UsuarioCrea, Nullable<System.DateTime> acrol_FechaCrea)
        {
            var acrol_IdParameter = acrol_Id.HasValue ?
                new ObjectParameter("acrol_Id", acrol_Id) :
                new ObjectParameter("acrol_Id", typeof(int));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var obj_IdParameter = obj_Id.HasValue ?
                new ObjectParameter("obj_Id", obj_Id) :
                new ObjectParameter("obj_Id", typeof(int));
    
            var acrol_UsuarioCreaParameter = acrol_UsuarioCrea.HasValue ?
                new ObjectParameter("acrol_UsuarioCrea", acrol_UsuarioCrea) :
                new ObjectParameter("acrol_UsuarioCrea", typeof(int));
    
            var acrol_FechaCreaParameter = acrol_FechaCrea.HasValue ?
                new ObjectParameter("acrol_FechaCrea", acrol_FechaCrea) :
                new ObjectParameter("acrol_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbAccesoRol_Update", acrol_IdParameter, rol_IdParameter, obj_IdParameter, acrol_UsuarioCreaParameter, acrol_FechaCreaParameter);
        }
    
        public virtual int UDP_Seg_tbBitacoraErrores_Insert(string bite_Pantalla, string bite_Usuario, Nullable<System.DateTime> bite_Fecha, string bite_MensajeError, string bite_Accion)
        {
            var bite_PantallaParameter = bite_Pantalla != null ?
                new ObjectParameter("bite_Pantalla", bite_Pantalla) :
                new ObjectParameter("bite_Pantalla", typeof(string));
    
            var bite_UsuarioParameter = bite_Usuario != null ?
                new ObjectParameter("bite_Usuario", bite_Usuario) :
                new ObjectParameter("bite_Usuario", typeof(string));
    
            var bite_FechaParameter = bite_Fecha.HasValue ?
                new ObjectParameter("bite_Fecha", bite_Fecha) :
                new ObjectParameter("bite_Fecha", typeof(System.DateTime));
    
            var bite_MensajeErrorParameter = bite_MensajeError != null ?
                new ObjectParameter("bite_MensajeError", bite_MensajeError) :
                new ObjectParameter("bite_MensajeError", typeof(string));
    
            var bite_AccionParameter = bite_Accion != null ?
                new ObjectParameter("bite_Accion", bite_Accion) :
                new ObjectParameter("bite_Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbBitacoraErrores_Insert", bite_PantallaParameter, bite_UsuarioParameter, bite_FechaParameter, bite_MensajeErrorParameter, bite_AccionParameter);
        }
    
        public virtual int UDP_Seg_tbObjeto_Insert(string obj_Pantalla, string obj_Referencia, Nullable<int> obj_UsuarioCrea, Nullable<System.DateTime> obj_FechaCrea)
        {
            var obj_PantallaParameter = obj_Pantalla != null ?
                new ObjectParameter("obj_Pantalla", obj_Pantalla) :
                new ObjectParameter("obj_Pantalla", typeof(string));
    
            var obj_ReferenciaParameter = obj_Referencia != null ?
                new ObjectParameter("obj_Referencia", obj_Referencia) :
                new ObjectParameter("obj_Referencia", typeof(string));
    
            var obj_UsuarioCreaParameter = obj_UsuarioCrea.HasValue ?
                new ObjectParameter("obj_UsuarioCrea", obj_UsuarioCrea) :
                new ObjectParameter("obj_UsuarioCrea", typeof(int));
    
            var obj_FechaCreaParameter = obj_FechaCrea.HasValue ?
                new ObjectParameter("obj_FechaCrea", obj_FechaCrea) :
                new ObjectParameter("obj_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbObjeto_Insert", obj_PantallaParameter, obj_ReferenciaParameter, obj_UsuarioCreaParameter, obj_FechaCreaParameter);
        }
    
        public virtual int UDP_Seg_tbObjeto_Update(Nullable<int> obj_Id, string obj_Pantalla, string obj_Referencia, Nullable<int> obj_UsuarioCrea, Nullable<System.DateTime> obj_FechaCrea, Nullable<int> obj_UsuarioModifica, Nullable<System.DateTime> obj_FechaModifica)
        {
            var obj_IdParameter = obj_Id.HasValue ?
                new ObjectParameter("obj_Id", obj_Id) :
                new ObjectParameter("obj_Id", typeof(int));
    
            var obj_PantallaParameter = obj_Pantalla != null ?
                new ObjectParameter("obj_Pantalla", obj_Pantalla) :
                new ObjectParameter("obj_Pantalla", typeof(string));
    
            var obj_ReferenciaParameter = obj_Referencia != null ?
                new ObjectParameter("obj_Referencia", obj_Referencia) :
                new ObjectParameter("obj_Referencia", typeof(string));
    
            var obj_UsuarioCreaParameter = obj_UsuarioCrea.HasValue ?
                new ObjectParameter("obj_UsuarioCrea", obj_UsuarioCrea) :
                new ObjectParameter("obj_UsuarioCrea", typeof(int));
    
            var obj_FechaCreaParameter = obj_FechaCrea.HasValue ?
                new ObjectParameter("obj_FechaCrea", obj_FechaCrea) :
                new ObjectParameter("obj_FechaCrea", typeof(System.DateTime));
    
            var obj_UsuarioModificaParameter = obj_UsuarioModifica.HasValue ?
                new ObjectParameter("obj_UsuarioModifica", obj_UsuarioModifica) :
                new ObjectParameter("obj_UsuarioModifica", typeof(int));
    
            var obj_FechaModificaParameter = obj_FechaModifica.HasValue ?
                new ObjectParameter("obj_FechaModifica", obj_FechaModifica) :
                new ObjectParameter("obj_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbObjeto_Update", obj_IdParameter, obj_PantallaParameter, obj_ReferenciaParameter, obj_UsuarioCreaParameter, obj_FechaCreaParameter, obj_UsuarioModificaParameter, obj_FechaModificaParameter);
        }
    
        public virtual int UDP_Seg_tbObjeto_Update_Estado(Nullable<int> obj_Id, Nullable<bool> obj_Estado, Nullable<int> obj_UsuarioModifica, Nullable<System.DateTime> obj_FechaModifica)
        {
            var obj_IdParameter = obj_Id.HasValue ?
                new ObjectParameter("obj_Id", obj_Id) :
                new ObjectParameter("obj_Id", typeof(int));
    
            var obj_EstadoParameter = obj_Estado.HasValue ?
                new ObjectParameter("obj_Estado", obj_Estado) :
                new ObjectParameter("obj_Estado", typeof(bool));
    
            var obj_UsuarioModificaParameter = obj_UsuarioModifica.HasValue ?
                new ObjectParameter("obj_UsuarioModifica", obj_UsuarioModifica) :
                new ObjectParameter("obj_UsuarioModifica", typeof(int));
    
            var obj_FechaModificaParameter = obj_FechaModifica.HasValue ?
                new ObjectParameter("obj_FechaModifica", obj_FechaModifica) :
                new ObjectParameter("obj_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbObjeto_Update_Estado", obj_IdParameter, obj_EstadoParameter, obj_UsuarioModificaParameter, obj_FechaModificaParameter);
        }
    
        public virtual int UDP_Seg_tbRol_Inactivar(Nullable<int> iDRol, Nullable<int> rol_UsuarioModifica, Nullable<System.DateTime> rol_FechaModifica)
        {
            var iDRolParameter = iDRol.HasValue ?
                new ObjectParameter("IDRol", iDRol) :
                new ObjectParameter("IDRol", typeof(int));
    
            var rol_UsuarioModificaParameter = rol_UsuarioModifica.HasValue ?
                new ObjectParameter("rol_UsuarioModifica", rol_UsuarioModifica) :
                new ObjectParameter("rol_UsuarioModifica", typeof(int));
    
            var rol_FechaModificaParameter = rol_FechaModifica.HasValue ?
                new ObjectParameter("rol_FechaModifica", rol_FechaModifica) :
                new ObjectParameter("rol_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbRol_Inactivar", iDRolParameter, rol_UsuarioModificaParameter, rol_FechaModificaParameter);
        }
    
        public virtual int UDP_Seg_tbRol_Insert(string rol_Descripcion, Nullable<bool> rol_Estado, Nullable<int> rol_UsuarioCrea, Nullable<System.DateTime> rol_FechaCrea)
        {
            var rol_DescripcionParameter = rol_Descripcion != null ?
                new ObjectParameter("rol_Descripcion", rol_Descripcion) :
                new ObjectParameter("rol_Descripcion", typeof(string));
    
            var rol_EstadoParameter = rol_Estado.HasValue ?
                new ObjectParameter("rol_Estado", rol_Estado) :
                new ObjectParameter("rol_Estado", typeof(bool));
    
            var rol_UsuarioCreaParameter = rol_UsuarioCrea.HasValue ?
                new ObjectParameter("rol_UsuarioCrea", rol_UsuarioCrea) :
                new ObjectParameter("rol_UsuarioCrea", typeof(int));
    
            var rol_FechaCreaParameter = rol_FechaCrea.HasValue ?
                new ObjectParameter("rol_FechaCrea", rol_FechaCrea) :
                new ObjectParameter("rol_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbRol_Insert", rol_DescripcionParameter, rol_EstadoParameter, rol_UsuarioCreaParameter, rol_FechaCreaParameter);
        }
    
        public virtual int UDP_Seg_tbRol_Update(Nullable<int> rol_Id, string rol_Descripcion, Nullable<int> rol_UsuarioModifica, Nullable<System.DateTime> rol_FechaModifica)
        {
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var rol_DescripcionParameter = rol_Descripcion != null ?
                new ObjectParameter("rol_Descripcion", rol_Descripcion) :
                new ObjectParameter("rol_Descripcion", typeof(string));
    
            var rol_UsuarioModificaParameter = rol_UsuarioModifica.HasValue ?
                new ObjectParameter("rol_UsuarioModifica", rol_UsuarioModifica) :
                new ObjectParameter("rol_UsuarioModifica", typeof(int));
    
            var rol_FechaModificaParameter = rol_FechaModifica.HasValue ?
                new ObjectParameter("rol_FechaModifica", rol_FechaModifica) :
                new ObjectParameter("rol_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbRol_Update", rol_IdParameter, rol_DescripcionParameter, rol_UsuarioModificaParameter, rol_FechaModificaParameter);
        }
    
        public virtual int UDP_Seg_tbRolEstado_Update(Nullable<int> rol_Id, Nullable<bool> rol_Estado, Nullable<int> rol_UsuarioModifica, Nullable<System.DateTime> rol_FechaModifica)
        {
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var rol_EstadoParameter = rol_Estado.HasValue ?
                new ObjectParameter("rol_Estado", rol_Estado) :
                new ObjectParameter("rol_Estado", typeof(bool));
    
            var rol_UsuarioModificaParameter = rol_UsuarioModifica.HasValue ?
                new ObjectParameter("rol_UsuarioModifica", rol_UsuarioModifica) :
                new ObjectParameter("rol_UsuarioModifica", typeof(int));
    
            var rol_FechaModificaParameter = rol_FechaModifica.HasValue ?
                new ObjectParameter("rol_FechaModifica", rol_FechaModifica) :
                new ObjectParameter("rol_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbRolEstado_Update", rol_IdParameter, rol_EstadoParameter, rol_UsuarioModificaParameter, rol_FechaModificaParameter);
        }
    
        public virtual int UDP_Seg_tbRolesUsuario_Delete(Nullable<int> usu_Id, Nullable<int> rol_Id)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbRolesUsuario_Delete", usu_IdParameter, rol_IdParameter);
        }
    
        public virtual int UDP_Seg_tbRolesUsuario_Insert(Nullable<int> usu_Id, Nullable<int> rol_Id, Nullable<int> rolu_UsuarioCrea, Nullable<System.DateTime> rolu_FechaCrea)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var rolu_UsuarioCreaParameter = rolu_UsuarioCrea.HasValue ?
                new ObjectParameter("rolu_UsuarioCrea", rolu_UsuarioCrea) :
                new ObjectParameter("rolu_UsuarioCrea", typeof(int));
    
            var rolu_FechaCreaParameter = rolu_FechaCrea.HasValue ?
                new ObjectParameter("rolu_FechaCrea", rolu_FechaCrea) :
                new ObjectParameter("rolu_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbRolesUsuario_Insert", usu_IdParameter, rol_IdParameter, rolu_UsuarioCreaParameter, rolu_FechaCreaParameter);
        }
    
        public virtual int UDP_Seg_tbRolesUsuario_Update(Nullable<int> rolu_Id, Nullable<int> rol_Id, Nullable<int> usu_Id, Nullable<int> rolu_UsuarioCrea, Nullable<System.DateTime> rolu_FechaCrea)
        {
            var rolu_IdParameter = rolu_Id.HasValue ?
                new ObjectParameter("rolu_Id", rolu_Id) :
                new ObjectParameter("rolu_Id", typeof(int));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var rolu_UsuarioCreaParameter = rolu_UsuarioCrea.HasValue ?
                new ObjectParameter("rolu_UsuarioCrea", rolu_UsuarioCrea) :
                new ObjectParameter("rolu_UsuarioCrea", typeof(int));
    
            var rolu_FechaCreaParameter = rolu_FechaCrea.HasValue ?
                new ObjectParameter("rolu_FechaCrea", rolu_FechaCrea) :
                new ObjectParameter("rolu_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbRolesUsuario_Update", rolu_IdParameter, rol_IdParameter, usu_IdParameter, rolu_UsuarioCreaParameter, rolu_FechaCreaParameter);
        }
    
        public virtual int UDP_Seg_tbUsuario_Estado(Nullable<int> usu_Id, Nullable<bool> usu_EsActivo, string usu_RazonInactivo)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var usu_EsActivoParameter = usu_EsActivo.HasValue ?
                new ObjectParameter("usu_EsActivo", usu_EsActivo) :
                new ObjectParameter("usu_EsActivo", typeof(bool));
    
            var usu_RazonInactivoParameter = usu_RazonInactivo != null ?
                new ObjectParameter("usu_RazonInactivo", usu_RazonInactivo) :
                new ObjectParameter("usu_RazonInactivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbUsuario_Estado", usu_IdParameter, usu_EsActivoParameter, usu_RazonInactivoParameter);
        }
    
        public virtual int UDP_Seg_tbUsuario_Insert(string usu_NombreUsuario, string usu_Password, string usu_Nombres, string usu_Apellidos, string usu_Correo, Nullable<bool> usu_EsActivo, Nullable<bool> usu_EsAdministrador, Nullable<int> suc_Id, Nullable<short> emp_Id)
        {
            var usu_NombreUsuarioParameter = usu_NombreUsuario != null ?
                new ObjectParameter("usu_NombreUsuario", usu_NombreUsuario) :
                new ObjectParameter("usu_NombreUsuario", typeof(string));
    
            var usu_PasswordParameter = usu_Password != null ?
                new ObjectParameter("usu_Password", usu_Password) :
                new ObjectParameter("usu_Password", typeof(string));
    
            var usu_NombresParameter = usu_Nombres != null ?
                new ObjectParameter("usu_Nombres", usu_Nombres) :
                new ObjectParameter("usu_Nombres", typeof(string));
    
            var usu_ApellidosParameter = usu_Apellidos != null ?
                new ObjectParameter("usu_Apellidos", usu_Apellidos) :
                new ObjectParameter("usu_Apellidos", typeof(string));
    
            var usu_CorreoParameter = usu_Correo != null ?
                new ObjectParameter("usu_Correo", usu_Correo) :
                new ObjectParameter("usu_Correo", typeof(string));
    
            var usu_EsActivoParameter = usu_EsActivo.HasValue ?
                new ObjectParameter("usu_EsActivo", usu_EsActivo) :
                new ObjectParameter("usu_EsActivo", typeof(bool));
    
            var usu_EsAdministradorParameter = usu_EsAdministrador.HasValue ?
                new ObjectParameter("usu_EsAdministrador", usu_EsAdministrador) :
                new ObjectParameter("usu_EsAdministrador", typeof(bool));
    
            var suc_IdParameter = suc_Id.HasValue ?
                new ObjectParameter("suc_Id", suc_Id) :
                new ObjectParameter("suc_Id", typeof(int));
    
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbUsuario_Insert", usu_NombreUsuarioParameter, usu_PasswordParameter, usu_NombresParameter, usu_ApellidosParameter, usu_CorreoParameter, usu_EsActivoParameter, usu_EsAdministradorParameter, suc_IdParameter, emp_IdParameter);
        }
    
        public virtual int UDP_Seg_tbUsuario_PasswordRestore(Nullable<int> usu_Id, string usu_Password)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var usu_PasswordParameter = usu_Password != null ?
                new ObjectParameter("usu_Password", usu_Password) :
                new ObjectParameter("usu_Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbUsuario_PasswordRestore", usu_IdParameter, usu_PasswordParameter);
        }
    
        public virtual int UDP_Seg_tbUsuario_PasswordUpdate(Nullable<int> usu_Id, string usu_Password)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var usu_PasswordParameter = usu_Password != null ?
                new ObjectParameter("usu_Password", usu_Password) :
                new ObjectParameter("usu_Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbUsuario_PasswordUpdate", usu_IdParameter, usu_PasswordParameter);
        }
    
        public virtual int UDP_Seg_tbUsuario_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbUsuario_Select");
        }
    
        public virtual int UDP_Seg_tbUsuario_Update(Nullable<int> usu_Id, string usu_NombreUsuario, string usu_Nombres, string usu_Apellidos, string usu_Correo, Nullable<bool> usu_EsActivo, string usu_RazonInactivo, Nullable<bool> usu_EsAdministrador, Nullable<int> suc_Id, Nullable<short> emp_Id)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var usu_NombreUsuarioParameter = usu_NombreUsuario != null ?
                new ObjectParameter("usu_NombreUsuario", usu_NombreUsuario) :
                new ObjectParameter("usu_NombreUsuario", typeof(string));
    
            var usu_NombresParameter = usu_Nombres != null ?
                new ObjectParameter("usu_Nombres", usu_Nombres) :
                new ObjectParameter("usu_Nombres", typeof(string));
    
            var usu_ApellidosParameter = usu_Apellidos != null ?
                new ObjectParameter("usu_Apellidos", usu_Apellidos) :
                new ObjectParameter("usu_Apellidos", typeof(string));
    
            var usu_CorreoParameter = usu_Correo != null ?
                new ObjectParameter("usu_Correo", usu_Correo) :
                new ObjectParameter("usu_Correo", typeof(string));
    
            var usu_EsActivoParameter = usu_EsActivo.HasValue ?
                new ObjectParameter("usu_EsActivo", usu_EsActivo) :
                new ObjectParameter("usu_EsActivo", typeof(bool));
    
            var usu_RazonInactivoParameter = usu_RazonInactivo != null ?
                new ObjectParameter("usu_RazonInactivo", usu_RazonInactivo) :
                new ObjectParameter("usu_RazonInactivo", typeof(string));
    
            var usu_EsAdministradorParameter = usu_EsAdministrador.HasValue ?
                new ObjectParameter("usu_EsAdministrador", usu_EsAdministrador) :
                new ObjectParameter("usu_EsAdministrador", typeof(bool));
    
            var suc_IdParameter = suc_Id.HasValue ?
                new ObjectParameter("suc_Id", suc_Id) :
                new ObjectParameter("suc_Id", typeof(int));
    
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Seg_tbUsuario_Update", usu_IdParameter, usu_NombreUsuarioParameter, usu_NombresParameter, usu_ApellidosParameter, usu_CorreoParameter, usu_EsActivoParameter, usu_RazonInactivoParameter, usu_EsAdministradorParameter, suc_IdParameter, emp_IdParameter);
        }
    }
}
