//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WashEEntities : DbContext
    {
        public WashEEntities()
            : base("name=WashEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAcciones> tbAcciones { get; set; }
        public virtual DbSet<tbAccionRol> tbAccionRol { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbCategoriaServicios> tbCategoriaServicios { get; set; }
        public virtual DbSet<tbServicios> tbServicios { get; set; }
        public virtual DbSet<ServicioExterno> ServicioExterno { get; set; }
    
        public virtual ObjectResult<UDP_Persona_tbPersonas_Insert_Result> UDP_Persona_tbPersonas_Insert(string per_Identidad, string per_Nombres, string per_Apellidos, Nullable<System.DateTime> per_FechaNacimiento, string per_Telefono, string per_CorreoElectronico, Nullable<int> per_UsuarioCrea, Nullable<System.DateTime> per_FechaCrea)
        {
            var per_IdentidadParameter = per_Identidad != null ?
                new ObjectParameter("per_Identidad", per_Identidad) :
                new ObjectParameter("per_Identidad", typeof(string));
    
            var per_NombresParameter = per_Nombres != null ?
                new ObjectParameter("per_Nombres", per_Nombres) :
                new ObjectParameter("per_Nombres", typeof(string));
    
            var per_ApellidosParameter = per_Apellidos != null ?
                new ObjectParameter("per_Apellidos", per_Apellidos) :
                new ObjectParameter("per_Apellidos", typeof(string));
    
            var per_FechaNacimientoParameter = per_FechaNacimiento.HasValue ?
                new ObjectParameter("per_FechaNacimiento", per_FechaNacimiento) :
                new ObjectParameter("per_FechaNacimiento", typeof(System.DateTime));
    
            var per_TelefonoParameter = per_Telefono != null ?
                new ObjectParameter("per_Telefono", per_Telefono) :
                new ObjectParameter("per_Telefono", typeof(string));
    
            var per_CorreoElectronicoParameter = per_CorreoElectronico != null ?
                new ObjectParameter("per_CorreoElectronico", per_CorreoElectronico) :
                new ObjectParameter("per_CorreoElectronico", typeof(string));
    
            var per_UsuarioCreaParameter = per_UsuarioCrea.HasValue ?
                new ObjectParameter("per_UsuarioCrea", per_UsuarioCrea) :
                new ObjectParameter("per_UsuarioCrea", typeof(int));
    
            var per_FechaCreaParameter = per_FechaCrea.HasValue ?
                new ObjectParameter("per_FechaCrea", per_FechaCrea) :
                new ObjectParameter("per_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Persona_tbPersonas_Insert_Result>("UDP_Persona_tbPersonas_Insert", per_IdentidadParameter, per_NombresParameter, per_ApellidosParameter, per_FechaNacimientoParameter, per_TelefonoParameter, per_CorreoElectronicoParameter, per_UsuarioCreaParameter, per_FechaCreaParameter);
        }
    
        public virtual ObjectResult<UDP_Seg_tbUsuario_Insert_Result> UDP_Seg_tbUsuario_Insert(string usu_NombreUsuario, string usu_Password, Nullable<int> rol_Id, Nullable<int> per_Id, byte[] per_foto)
        {
            var usu_NombreUsuarioParameter = usu_NombreUsuario != null ?
                new ObjectParameter("usu_NombreUsuario", usu_NombreUsuario) :
                new ObjectParameter("usu_NombreUsuario", typeof(string));
    
            var usu_PasswordParameter = usu_Password != null ?
                new ObjectParameter("usu_Password", usu_Password) :
                new ObjectParameter("usu_Password", typeof(string));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var per_IdParameter = per_Id.HasValue ?
                new ObjectParameter("per_Id", per_Id) :
                new ObjectParameter("per_Id", typeof(int));
    
            var per_fotoParameter = per_foto != null ?
                new ObjectParameter("per_foto", per_foto) :
                new ObjectParameter("per_foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Seg_tbUsuario_Insert_Result>("UDP_Seg_tbUsuario_Insert", usu_NombreUsuarioParameter, usu_PasswordParameter, rol_IdParameter, per_IdParameter, per_fotoParameter);
        }
    }
}
