//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAccionRol
    {
        public int acrol_Id { get; set; }
        public int accion_Id { get; set; }
        public int rol_Id { get; set; }
    
        public virtual tbAcciones tbAcciones { get; set; }
        public virtual tbRoles tbRoles { get; set; }
    }
}
