//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCategoriaServicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCategoriaServicios()
        {
            this.tbServicios = new HashSet<tbServicios>();
        }
    
        public int cserv_Id { get; set; }
        public string cserv_Descripcion { get; set; }
        public Nullable<bool> cserv_Estado { get; set; }
        public string cserv_RazonInactivo { get; set; }
        public int cserv_UsuarioCrea { get; set; }
        public System.DateTime cserv_FechaCrea { get; set; }
        public Nullable<int> cserv_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> cserv_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbServicios> tbServicios { get; set; }
    }
}
