//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbServicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbServicios()
        {
            this.tbPedidosDetalle = new HashSet<tbPedidosDetalle>();
            this.tbSuscripciones = new HashSet<tbSuscripciones>();
        }
    
        public int serv_Id { get; set; }
        public int cserv_Id { get; set; }
        public string serv_Titulo { get; set; }
        public string serv_Descripcion { get; set; }
        public decimal serv_Precio { get; set; }
        public string serv_Directorio { get; set; }
        public bool serv_Estado { get; set; }
        public string serv_RazonInactivo { get; set; }
        public int serv_UsuarioCrea { get; set; }
        public System.DateTime serv_FechaCrea { get; set; }
        public Nullable<int> serv_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> serv_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPedidosDetalle> tbPedidosDetalle { get; set; }
        public virtual tbCategoriaServicios tbCategoriaServicios { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSuscripciones> tbSuscripciones { get; set; }
    }
}
