//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSuscripciones
    {
        public int sus_Id { get; set; }
        public string sus_Descripcion { get; set; }
        public decimal sus_Precio { get; set; }
        public int sus_CantidadMaximaSolicitudes { get; set; }
        public int serv_Id { get; set; }
        public int sus_MesesVigencia { get; set; }
        public bool sus_Estado { get; set; }
        public string sus_RazonInactivo { get; set; }
        public int sus_UsuarioCrea { get; set; }
        public System.DateTime sus_FechaCrea { get; set; }
        public Nullable<int> sus_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> sus_FechaModifica { get; set; }
    
        public virtual tbServicios tbServicios { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
