//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsuarios()
        {
            this.tbPersonas1 = new HashSet<tbPersonas>();
            this.tbPersonas2 = new HashSet<tbPersonas>();
            this.SolicitudesApartadas = new HashSet<SolicitudesApartadas>();
            this.tbCategoriaServicios = new HashSet<tbCategoriaServicios>();
            this.tbCategoriaServicios1 = new HashSet<tbCategoriaServicios>();
            this.tbServicios = new HashSet<tbServicios>();
            this.tbServicios1 = new HashSet<tbServicios>();
        }
    
        public int usu_Id { get; set; }
        public string usu_NombreDeUsuario { get; set; }
        public string usu_Contrasenia { get; set; }
        public Nullable<int> rol_id { get; set; }
        public Nullable<int> per_Id { get; set; }
        public byte[] usu_Fotografia { get; set; }
    
        public virtual tbPersonas tbPersonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPersonas> tbPersonas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPersonas> tbPersonas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudesApartadas> SolicitudesApartadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCategoriaServicios> tbCategoriaServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCategoriaServicios> tbCategoriaServicios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbServicios> tbServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbServicios> tbServicios1 { get; set; }
        public virtual tbRoles tbRoles { get; set; }
    }
}
